# **Numpy** **Basics** ⌛

**Consider the below code to answer further questions:**
```
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
```

**Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.**

Yes, there is a difference in the data types of **list_** and **array_list**.

**list_** is a Python list with string elements.

**array_list** is a NumPy array created from the list, but containing string data type.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']

array_list = np.array(object = list_)

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


So **list_** is of type list and **array_list** is of type numpy.ndarray.

The main differences between a Python list and NumPy array are:



*   NumPy arrays have fixed size at creation, lists can grow dynamically.
*   NumPy arrays are homogeneous - all elements must be of same data type. Lists can have different data types in each element.


*   NumPy arrays support vectorized operations like element-wise math. Lists don't have built-in math operations.

So in this case, **array_list** contains string data like the original list, but stored in a fixed-size NumPy array.






**Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.**

To print the data type of each element in both list_ and array_list:

In [3]:
for i in list_:
  print(type(i))

for i in array_list:
  print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


The key difference is that list_ will contain string elements, while array_list will contain numpy.str_ elements since it is a NumPy array.

**Q3. Considering the following changes in the variable, array_list:**


```
array_list = np.array(object = list_, dtype = int)
```



Now array_list is a NumPy array with integer dtype, while list_ remains a Python list with string elements. To print the data types:

In [4]:
for i in list_:
  print(type(i))

for i in array_list:
  print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


So now list_ contains strings, while array_list contains integers due to the specified dtype.

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:


```
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
```

In [5]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print(type(num_list[0][0]))
print(type(num_array[0][0]))
for i in range(len(num_list)):
  for j in range(len(num_list[i])):
    print(type(num_list[i][j]))

for i in range(num_array.shape[0]):
  for j in range(num_array.shape[1]):
    print(type(num_array[i][j]))


<class 'int'>
<class 'numpy.int64'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


**Q4. Write a code to find the following characteristics of variable, num_array:**

(i)shape

(ii)size

In [6]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# Shape of num_array
print(num_array.shape)

# Size of num_array
print(num_array.size)

(2, 3)
6


**Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.**

In [7]:
import numpy as np

# Create 3x3 array of zeros
zero_array = np.zeros((3,3))

print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Q6. Create an identity matrix of shape (5,5) using numpy functions?**

In [8]:
import numpy as np

identity_matrix = np.eye(N=5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
